### ISSUE TITLE
Is it reasonable to use pseudolabeling for expanding the train data?

### ISSUE THREAD

**Issue by songkq** [qubvel/open-cities-challenge#1]
Hi @qubvel , 
`Take predictions from previous stage and prepare them to use as training data for current stage. This technique is called pseudolabeling (when we use models prediction for training).`

I wonder if it is always allowed to expand the train data `with pseudolabels generated by test data using pseudolabeling`? Or the trick is only allowed in this competetion track. It seems somewhat to make the model` overfit the test dataset`.

**Comment by qubvel** [comment]
It is a tricky technique, however it became a must for winning in a recent years for different competitions. You should be careful using it, because it can amplify a noise in our data if your models ensemble is weak. However in this competition, there were enough data and models perform well, so I was able to improve generalization using pseudolabels.

**Comment by songkq** [comment]
@qubvel Many thanks.
